version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPO_URI=365998109313.dkr.ecr.ap-south-1.amazonaws.com/braintaskapp
      - echo $REPO_URI
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPO_URI
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      # add your container name
      - DOCKER_CONTAINER_NAME=braintaskapp
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'

